name: Deploy StoryBook

on: 
  push:
    branch:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run : npm ci --no-save --legacy-peer-deps --force

      - name: Build Storybook
        run: npm build-storybook

      - name: Deploy
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env: 
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}